#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parsing electrochemical data from vanadium flow battery experiments
generated by ES8 software (www.potentiostat.ru)

@author: Andrey Novikov, Nikita Buriak, Ilia Khristoforov
"""

import sys
import argparse
import pathlib
import re
from enum import Enum
from base_parser import ExperStep, BaseParser


class ElinsParser(BaseParser):
    def read_data(self, file_path_in: pathlib.Path) -> list[ExperStep]:
        """
        Reads electrochemical data from an ES8 potentiostat file.

        Args:
            file_path_in (pathlib.Path): Path to the input data file (e.g., 'potentiostat.txt').

        Returns:
            list[ExperStep]: A list of ExperStep objects containing the parsed data.
        """
        file = file_path_in.open('r', encoding='cp1251')
    
        data: list[ExperStep] = []
    
        class State(Enum):
            BLOCK_START = 1
            BLOCK_HEADER_START = 2
            STEP_START = 3
            DATA_START = 4
            VALUES = 5
    
        state: State = State.BLOCK_START
        nblock: int = -1
        ncycle: int = -1
        nstep: int = -1
    
        file.readline()  # Skip first line
        nline: int = 1
        for line in file:
            nline += 1
            line = line.rstrip('\n')
    
            if state == State.BLOCK_START:
                if not line:
                    state = State.BLOCK_HEADER_START
                continue
            
            if state == State.BLOCK_HEADER_START:
                if line:
                    r = re.fullmatch(r'Блок ([0-9]+)\w+', line) # Regex to match block header
                    if r:
                        nblock = int(r.group(1))
                        # print(f"Block: №{nblock}")
                    else:
                        print(f"Unexpected block header '{line}' at line #{nline}")
                        sys.exit(1)
                    state = State.STEP_START
                continue
            
            if state == State.STEP_START:
                r = re.fullmatch(r'Цикл ([0-9]+), Шаг ([0-9]+)', line)
                if r:
                    ncycle = int(r.group(1))
                    nstep = int(r.group(2))
                    state = State.DATA_START
                continue
            
            if state == State.DATA_START:
                if not re.fullmatch(r'Время, с.,[ ]+Потенциал, В,[ ]+Ток, А', line):
                    print(f"Unexpected values header at line #{nline}")
                    sys.exit(1)
                data.append(ExperStep(index=(nblock, ncycle, nstep), t=[], U=[], I=[], Q=[]))
                state = State.VALUES
                continue
            
            if state == State.VALUES:
                if not line:
                    state = State.STEP_START
                    continue
                elif line == 'u':
                    state = State.BLOCK_START
                    continue
                
                vals = [float(s.replace(',', '.')) for s in line.split()]
                data[-1].t.append(vals[0])
                data[-1].U.append(vals[1])
                data[-1].I.append(vals[2])
                data[-1].Q.append(float('nan'))
    
            self.data = data
        return data


def main():
    """
    Main function to parse ES8 experimental data.

    It reads raw data from a specified experiment file, processes it,
    and writes the parsed data to a CSV file.
    """
    parser = argparse.ArgumentParser(
        prog="parse-VRFB-ES8-data",
        description="Parsing of potentiostat ES8 experimental data for vanadium flow batteries",
        epilog="(c) FlowBat team, Skoltech"
        )
    parser.add_argument('experiment_folder', metavar="EXPERIMENT_FOLDER",
                        help='experiment folder containing raw data, config.json, etc.')
    args = parser.parse_args()

    experiment_folder = pathlib.Path(args.experiment_folder)
    file_in = experiment_folder / '01_Raw_data' / 'potentiostat' / 'potentiostat.txt'
    file_out = experiment_folder / '02_Parsed_data' / 'potentiostat' / 'cycles.txt'

    elins_parser = ElinsParser(experiment_folder)

    # Read input file
    print(":::")
    print(f"::: Reading ES8 experimental data from '{str(file_in)}'")
    print(":::")
    elins_parser.read_data(file_in)

    # Process file
    elins_parser.process_data(elins_parser.data)

    # Write output file
    print(":::")
    print(f"::: Writing processed data to '{str(file_out)}'")
    print(":::")
    elins_parser.write_csv_data(elins_parser.data, file_out)
# ---


if __name__ == '__main__':
    main()
    # test()
